AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  ImageId:
    Type: String
    Description: ""
    Default: ami-089f338f3a2e69431
  InstanceType:
    Type: String
    Description: ""
    Default: t3.medium
  KeyName:
    Type: String
    Description: ""
    Default: smartanalyst-asset-prioritization-dev-res
  Tenancy:
    Type: String
    Description: ""
    Default: default
  SubnetId:
    Type: String
    Description: ""
    Default: subnet-04dc03b2012e92618
  SecurityGroupId1:
    Type: String
    Description: ""
    Default: sg-09cc609a45cb00b04
  SecurityGroupId2:
    Type: String
    Description: ""
    Default: sg-00e6529658d9910d2
  IamInstanceProfile:
    Type: String
    Description: ""
    Default: smartanalyst-asset-prioritization-eks-admin-role
  EBSDeviceName:
    Type: String
    Description: ""
    Default: /dev/xvda
  EBSVolumeSize:
    Type: Number
    Description: ""
    Default: 100
  EBSSnapshotId:
    Type: String
    Description: ""
    Default: snap-0edded61b626cb66c
  EBSVolumeType:
    Type: String
    Description: ""
    Default: gp2
  CpuCoreCount:
    Type: Number
    Description: ""
    Default: 1
  CpuThreadsPerCore:
    Type: Number
    Description: ""
    Default: 2
  TagKey:
    Type: String
    Description: ""
    Default: Name
  TagValue:
    Type: String
    Description: ""
    Default: apt-dev-ec2-web-app
  TagKey1:
    Type: String
    Description: ""
    Default: Type
  TagValue1:
    Type: String
    Description: ""
    Default: web-app
  TagKey2:
    Type: String
    Description: ""
    Default: env
  TagValue2:
    Type: String
    Description: ""
    Default: dev
  TagKey3:
    Type: String
    Description: ""
    Default: cost_center
  TagValue3:
    Type: String
    Description: ""
    Default: apt   

Resources:
    EC2Instance2:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: !Ref ImageId
            InstanceType: !Ref InstanceType
            KeyName: !Ref KeyName
            AvailabilityZone: !Sub "${AWS::Region}a"
            Tenancy: !Ref Tenancy
            SubnetId: !Ref SubnetId
            EbsOptimized: true
            SecurityGroupIds: 
              - !Ref SecurityGroupId1
              - !Ref SecurityGroupId2
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: !Ref EBSDeviceName
                Ebs: 
                    Encrypted: false
                    VolumeSize: !Ref EBSVolumeSize
                    SnapshotId: !Ref EBSSnapshotId
                    VolumeType: !Ref EBSVolumeType
                    DeleteOnTermination: true
            IamInstanceProfile: !ImportValue 
                   'Fn::Sub': '${StackNameExport}-InstanceProfileName'
            Tags:
              - Key: !Ref TagKey
                Value: !Ref TagValue
              - Key: !Ref TagKey1
                Value: !Ref TagValue1
              - Key: !Ref TagKey2 
                Value: !Ref TagValue2
              - Key: !Ref TagKey3 
                Value: !Ref TagValue3 
            HibernationOptions: 
                Configured: false
            CpuOptions: 
                CoreCount: !Ref CpuCoreCount
                ThreadsPerCore: !Ref CpuThreadsPerCore
            EnclaveOptions: 
                Enabled: false