AWSTemplateFormatVersion: "2010-09-09"
Description: "DMS ReplicationInstance,SubnetGroup and SecurityGroup"
Parameters:     
  ReplicationInstanceName:
    Type: String
    Description: "Replication Instance name."
    Default: ceat-mdp-repl-dms-instance
  InstanceClass:
    Type: String
    Description: "Replication Instance Class."
    Default: "dms.r5.large"  
  RepStorage:
    Type: Number
    Description: "Replication Instance Allocated Storage."
    Default: 512 
  MaintenanceWindow: 
    Type: String
    Description: "Replication Instance Preffered Maintenance Window."
    Default: "tue:11:52-tue:12:22"
  RepEngineVersion:
    Type: String
    Description: "Replication Instance Engine Version."
    Default: "3.4.6"      
  EC2SecurityGroupName:
    Type: String
    Description: "EC2 Security Group Name."
    Default: ceat-mdp-dms-sec-group-test
  VPCid:
    Type: String
    Description: "VPC Id used by EC2"
    Default: vpc-037fdf874a7669a3f   
  DMSReplicationSubnetGroupName:
    Type: String
    Description: "DMS Replication Subnet Group Name"
    Default: ceat-mdp-dms-subnet-group
  Subnetid1:
    Type: String
    Description: "Subnet id 1 of DMS Replication Subnet Group/ceat-mdp-prd-priv-subnet-app-a1"
    Default: subnet-0c2260fd42915a4d2
  Subnetid2:
    Type: String
    Description: "Subnet id 2 of DMS Replication Subnet Group/ceat-mdp-prd-priv-subnet-app-b1"
    Default: subnet-062d9b4fd39944666
  Subnetid3:
   Type: String
   Description: "Subnet id 3 of DMS Replication Subnet Group/ceat-mdp-prd-priv-subnet-app-c1"
   Default: subnet-0026e351ccebbe856 
  TagKey:
    Type: String
    Description: "Tag Key"
    Default: Lighthouse
  TagValue:
    Type: String
    Description: "Tag Value"
    Default: ceat-mdp  
  StackNameExport:
    Type: String
    Description: "Name of stack from where DMS Role ARN is exported"
    Default: IAM-prod      
  
Resources:
    DMSReplicationInstance:
        Type: "AWS::DMS::ReplicationInstance"
        Properties:
            ReplicationInstanceIdentifier: !Ref ReplicationInstanceName
            ReplicationInstanceClass: !Ref InstanceClass
            AllocatedStorage: !Ref RepStorage
            VpcSecurityGroupIds: 
              - !Ref EC2SecurityGroup
            AvailabilityZone: !Sub "${AWS::Region}a"
            ReplicationSubnetGroupIdentifier: !Ref DMSReplicationSubnetGroupName
            Tags: 
              - 
                Key: !Ref TagKey
                Value: !Ref TagValue
            PreferredMaintenanceWindow: !Ref MaintenanceWindow
            MultiAZ: false
            EngineVersion: !Ref RepEngineVersion
            AutoMinorVersionUpgrade: true
            PubliclyAccessible: false
        DependsOn: DMSReplicationSubnetGroup

    EC2SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "ceat-mdp-dms-sec-group"
            GroupName: !Ref EC2SecurityGroupName
            Tags: 
              - 
                Key: !Ref TagKey
                Value: !Ref TagValue
            VpcId: !Ref VPCid
            SecurityGroupIngress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"
                
              
    DMSReplicationSubnetGroup:
        Type: "AWS::DMS::ReplicationSubnetGroup"
        Properties:
            ReplicationSubnetGroupIdentifier: !Ref DMSReplicationSubnetGroupName
            ReplicationSubnetGroupDescription: "ceat-mdp-dms-subnet-group"
            Tags:
              -
                Key: !Ref TagKey
                Value: !Ref TagValue
            SubnetIds:
              - !Ref Subnetid1
              - !Ref Subnetid2
              - !Ref Subnetid3

Outputs: 
  DMSReplicationInstance:
    Description: DMS Replication Instance
    Value: !Ref DMSReplicationInstance
    Export:
      Name:
       'Fn::Sub': '${AWS::StackName}-DMSRepInstanceArn'
  SecurityGroup:
    Description: EC2 Security Group
    Value: !Ref EC2SecurityGroup
  SubnetGroup:
    Description: DMS Replication Subnet Group
    Value: !Ref DMSReplicationSubnetGroup

    